set-option -g default-shell /bin/bash

set -g default-terminal "tmux-256color" 

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g mode-keys vi
set -sg escape-time 10

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

bind -T prefix h select-pane -L
bind -T prefix j select-pane -D
bind -T prefix k select-pane -U
bind -T prefix l select-pane -R

bind -n M-h resize-pane -L 5
bind -n M-j resize-pane -D 5
bind -n M-k resize-pane -U 5
bind -n M-l resize-pane -R 5

set -g status-left-length 40
set -g status-left " [#S] "
set -g status-right " #(awk '{print int($1/3600)\"h\"int(($1%%3600)/60)\"m\"}' /proc/uptime) "

bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "sh -c '\
  if command -v clip.exe >/dev/null 2>&1; then clip.exe; \
  elif command -v wl-copy >/dev/null 2>&1; then wl-copy; \
  elif command -v xclip >/dev/null 2>&1; then xclip -in -selection clipboard; \
  elif command -v xsel >/dev/null 2>&1; then xsel --clipboard --input; \
  else cat >/dev/null; fi'"
